Disable linting in workflow

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -64,10 +64,10 @@ jobs:
       - name: Install dependencies
         run: make install
 
-      - name: Linting
-        id: lint
-        if: ${{ success() || failure() }}
-        run: make lint
+#      - name: Linting
+#        id: lint
+#        if: ${{ success() || failure() }}
+#        run: make lint
 
       - name: i18n sync
         id: i18n
